# scripts/taco-micros/equivalentes.py
# Liga os alimentos do time master (catálogo CUSTOM, sem micronutrientes) ao ALIMENTO EQUIVALENTE da TACO.
# Cada linha: nome do alimento | kcal, prot, carbo, gord (do cadastro) | nome exato na TACO | observação
# O gerador só aceita a ligação se as calorias forem parecidas (<= 40% ou <= 20 kcal de diferença) -- senão o
# alimento fica "sem dados" em vez de mostrar micronutrientes de outro alimento.
LINKS = [
 ('Abacaxi', 50, 'Abacaxi, cru', ''), ('Abobrinha', 17, 'Abobrinha, italiana, crua', ''), ('Abóbora (Cabotiá)', 34, 'Abóbora, cabotian, crua', ''),
 ('Agrião', 11, 'Agrião, cru', ''), ('Alcatra Grelhada', 240, 'Carne, bovina, miolo de alcatra, sem gordura, grelhado', ''),
 ('Alface (Qualquer tipo)', 14, 'Alface, crespa, crua', ''), ('Arroz Branco', 130, 'Arroz, tipo 1, cozido', ''),
 ('Arroz Integral', 111, 'Arroz, integral, cozido', ''), ('Arroz Parboilizado', 123, 'Arroz, tipo 1, cozido', 'TACO não tem parboilizado'),
 ('Atum (Grelhado ou Assado)', 130, 'Atum, fresco, cru', ''), ('Aveia em Flocos', 380, 'Aveia, flocos, crua', ''),
 ('Azeite de Oliva', 884, 'Azeite, de oliva, extra virgem', ''), ('Bacon Frito', 540, 'Toucinho, frito', ''),
 ('Banana', 89, 'Banana, prata, crua', ''), ('Batata Doce Cozida', 86, 'Batata, doce, cozida', ''), ('Batata Doce Assada', 118, 'Batata, doce, cozida', 'assada ~ cozida'),
 ('Batata Inglesa Cozida', 86, 'Batata, inglesa, cozida', ''), ('Berinjela', 25, 'Berinjela, crua', ''), ('Beterraba', 43, 'Beterraba, crua', ''),
 ('Brócolis (Cozido)', 25, 'Brócolis, cozido', ''), ('Café sem Açúcar', 0, 'Café, infusão 10%', ''), ('Camarão Grelhado', 100, 'Camarão, Rio Grande, grande, cozido', ''),
 ('Carne Moída (Patinho)', 219, 'Carne, bovina, patinho, sem gordura, grelhado', ''), ('Carne Seca / Charque (Desfiada)', 280, 'Carne, bovina, charque, cozido', ''),
 ('Carne de Panela (Cozida)', 220, 'Carne, bovina, acém, sem gordura, cozido', ''), ('Castanha do Pará', 650, 'Castanha-do-Brasil, crua', ''),
 ('Cebola', 40, 'Cebola, crua', ''), ('Cenoura (Cozida)', 35, 'Cenoura, cozida', ''), ('Chocolate Meio Amargo (70%)', 540, 'Chocolate, meio amargo', ''),
 ('Chuchu', 19, 'Chuchu, cru', ''), ('Chá sem Açúcar', 0, 'Chá, preto, infusão 5%', ''), ('Clara de Ovo', 52, 'Ovo, de galinha, clara, cozida/10minutos', ''),
 ('Couve (Manteiga)', 35, 'Couve, manteiga, crua', ''), ('Couve-flor', 25, 'Couve-flor, crua', ''), ('Cream Cheese Light', 200, 'Queijo, requeijão, cremoso', 'aproximado (TACO não tem cream cheese)'),
 ('Cuscuz de Milho', 112, 'Cuscuz, de milho, cozido com sal', ''), ('Espinafre', 23, 'Espinafre, Nova Zelândia, cru', ''),
 ('Farinha de Linhaça', 534, 'Linhaça, semente', 'semente, não a farinha'), ('Feijão Carioca Cozido', 76, 'Feijão, carioca, cozido', ''),
 ('Feijão Preto Cozido', 91, 'Feijão, preto, cozido', ''), ('Filé Mignon Grelhado', 260, 'Carne, bovina, filé mingnon, sem gordura, grelhado', ''),
 ('Frango Desfiado (Cozido)', 165, 'Frango, peito, sem pele, cozido', ''), ('Frango Grelhado', 165, 'Frango, peito, sem pele, grelhado', ''),
 ('Inhame (Cozido)', 118, 'Inhame, cru', 'a TACO só traz inhame cru'), ('Iogurte Natural Desnatado', 40, 'Iogurte, natural, desnatado', ''),
 ('Kiwi', 61, 'Kiwi, cru', ''), ('Laranja', 47, 'Laranja, pêra, crua', ''), ('Leite Desnatado', 35, 'Leite, de vaca, desnatado, UHT', ''),
 ('Leite Integral', 60, 'Leite, de vaca, integral', ''), ('Leite Zero Lactose', 60, 'Leite, de vaca, integral', 'zero lactose ~ integral'),
 ('Lentilha Cozida', 116, 'Lentilha, cozida', ''), ('Mamão', 43, 'Mamão, Papaia, cru', ''), ('Mandioca Cozida', 114, 'Mandioca, cozida', ''),
 ('Mandioquinha / Batata Baroa', 100, 'Batata, baroa, cozida', ''), ('Manteiga', 717, 'Manteiga, com sal', ''), ('Maçã', 52, 'Maçã, Fuji, com casca, crua', ''),
 ('Melancia', 30, 'Melancia, crua', ''), ('Melão', 34, 'Melão, cru', ''), ('Morango', 32, 'Morango, cru', ''),
 ('Músculo (Cozido)', 220, 'Carne, bovina, músculo, sem gordura, cozido', ''), ('Nozes', 650, 'Noz, crua', ''),
 ('Ovos Inteiros', 143, 'Ovo, de galinha, inteiro, cozido/10minutos', ''), ('Ovos Mexidos', 160, 'Ovo, de galinha, inteiro, cozido/10minutos', 'mexido ~ cozido (sem a gordura do preparo)'),
 ('Pasta de Amendoim', 588, 'Amendoim, torrado, salgado', 'aproximado: a TACO não tem pasta de amendoim'), ('Patinho (Cozido / Iscas)', 219, 'Carne, bovina, patinho, sem gordura, grelhado', ''),
 ('Paçoca (Rolha)', 490, 'Paçoca, amendoim', ''), ('Peito de Peru Grelhado', 150, 'Peru, congelado, assado', ''), ('Pepino (Com casca)', 15, 'Pepino, cru', ''),
 ('Pera', 57, 'Pêra, Williams, crua', ''), ('Pescada Branca Grelhada', 110, 'Pescada, branca, crua', ''), ('Pimentão', 20, 'Pimentão, verde, cru', ''),
 ('Presunto Magro', 105, 'Presunto, sem capa de gordura', ''), ('Pão Francês', 300, 'Pão, trigo, francês', ''), ('Pão Integral', 250, 'Pão, trigo, forma, integral', ''),
 ('Queijo Minas Padrão', 264, 'Queijo, minas, frescal', ''), ('Queijo Mussarela Light', 260, 'Queijo, mozarela', 'light ~ tradicional (aproximado)'),
 ('Queijo Mussarela Tradicional', 330, 'Queijo, mozarela', ''), ('Queijo Ricota Fresca', 140, 'Queijo, ricota', ''), ('Repolho', 25, 'Repolho, branco, cru', ''),
 ('Requeijão Light', 180, 'Queijo, requeijão, cremoso', 'light ~ tradicional (aproximado)'), ('Rúcula', 25, 'Rúcula, crua', ''),
 ('Salmão Grelhado', 200, 'Salmão, sem pele, fresco, grelhado', ''), ('Sobrecoxa de Frango (Sem pele)', 210, 'Frango, sobrecoxa, sem pele, assada', ''),
 ('Tangerina', 53, 'Tangerina, Poncã, crua', ''), ('Tapioca (Goma)', 330, 'Fécula, de mandioca', 'goma de tapioca = fécula de mandioca'),
 ('Tofu (Queijo de Soja)', 76, 'Soja, queijo (tofu)', ''), ('Tomate', 18, 'Tomate, com semente, cru', ''), ('Uva', 69, 'Uva, Itália, crua', ''),
 ('Vagem', 31, 'Vagem, crua', ''), ('Água de Coco', 22, 'Coco, água de', ''),
]
