import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const exercises = [
  // --- ABDÔMEN ---
  { name: 'Abdominal ball-pass', category: 'Abdômen' },
  { name: 'Abdominal canivete', category: 'Abdômen' },
  { name: 'Abdominal crunch', category: 'Abdômen' },
  { name: 'Abdominal crunch c/pernas apoiadas', category: 'Abdômen' },
  { name: 'Abdominal crunch c/pernas elevadas', category: 'Abdômen' },
  { name: 'Abdominal crunch no colchonete', category: 'Abdômen' },
  { name: 'Abdominal infra c/bola', category: 'Abdômen' },
  { name: 'Abdominal infra na paralela', category: 'Abdômen' },
  { name: 'Abdominal infra no colchonete', category: 'Abdômen' },
  { name: 'Abdominal infra no espaldar', category: 'Abdômen' },
  { name: 'Abdominal máquina', category: 'Abdômen' },
  { name: 'Abdominal no banco', category: 'Abdômen' },
  { name: 'Abdominal no cross ajoelhado', category: 'Abdômen' },
  { name: 'Abdominal no cross em pé', category: 'Abdômen' },
  { name: 'Abdominal remador', category: 'Abdômen' },
  { name: 'Abdominal supra no banco declinado', category: 'Abdômen' },
  { name: 'Máquina de abdômen Seven', category: 'Abdômen' },
  { name: 'Prancha abdominal', category: 'Abdômen' },
  { name: 'Prancha com variação', category: 'Abdômen' },
  { name: 'Prancha isométrica', category: 'Abdômen' },
  { name: 'Prancha lateral', category: 'Abdômen' },
  { name: 'Rodinha abdominal', category: 'Abdômen' },

  // --- PEITO ---
  { name: 'Crucifixo inclinado c/halteres', category: 'Peito' },
  { name: 'Crucifixo reto c/halteres', category: 'Peito' },
  { name: 'Cross-over polia alta', category: 'Peito' },
  { name: 'Cross-over polia baixa', category: 'Peito' },
  { name: 'Flexão de braços', category: 'Peito' },
  { name: 'Flexão com joelhos apoiados', category: 'Peito' },
  { name: 'Peito na máquina', category: 'Peito' },
  { name: 'Supino articulado', category: 'Peito' },
  { name: 'Supino articulado inclinado', category: 'Peito' },
  { name: 'Supino articulado neutro', category: 'Peito' },
  { name: 'Supino declinado c/halteres', category: 'Peito' },
  { name: 'Supino inclinado c/barra', category: 'Peito' },
  { name: 'Supino inclinado c/halteres', category: 'Peito' },
  { name: 'Supino máquina', category: 'Peito' },
  { name: 'Supino no Smith', category: 'Peito' },
  { name: 'Supino reto c/barra', category: 'Peito' },
  { name: 'Supino reto c/halteres', category: 'Peito' },
  { name: 'Voador frontal', category: 'Peito' },
  { name: 'Voador frontal Cimerian', category: 'Peito' },

  // --- COSTAS ---
  { name: 'Barra fixa pegada aberta', category: 'Costas' },
  { name: 'Barra fixa pegada fechada', category: 'Costas' },
  { name: 'Barra livre', category: 'Costas' },
  { name: 'Graviton pegada aberta', category: 'Costas' },
  { name: 'Graviton pegada neutra fechada', category: 'Costas' },
  { name: 'Levantamento terra', category: 'Costas' },
  { name: 'Levantamento terra sumô', category: 'Costas' },
  { name: 'Lombar no banco romano', category: 'Costas' },
  { name: 'Pulldown máquina', category: 'Costas' },
  { name: 'Pulldown no cross barra', category: 'Costas' },
  { name: 'Pulldown no cross barrinha', category: 'Costas' },
  { name: 'Pulldown no cross corda', category: 'Costas' },
  { name: 'Puxada articulada', category: 'Costas' },
  { name: 'Puxada articulada aberta', category: 'Costas' },
  { name: 'Puxada c/triângulo', category: 'Costas' },
  { name: 'Puxada frente aberta', category: 'Costas' },
  { name: 'Puxada frente c/triângulo', category: 'Costas' },
  { name: 'Puxada frente pegada aberta pronada', category: 'Costas' },
  { name: 'Puxada frente pegada aberta neutra', category: 'Costas' },
  { name: 'Puxada máquina', category: 'Costas' },
  { name: 'Puxada supinada máquina', category: 'Costas' },
  { name: 'Remada alta no cross', category: 'Costas' },
  { name: 'Remada articulada', category: 'Costas' },
  { name: 'Remada articulada supinada', category: 'Costas' },
  { name: 'Remada baixa', category: 'Costas' },
  { name: 'Remada baixa c/triângulo', category: 'Costas' },
  { name: 'Remada cavalinho', category: 'Costas' },
  { name: 'Remada cavalinho pegada aberta', category: 'Costas' },
  { name: 'Remada cavalinho Seven', category: 'Costas' },
  { name: 'Remada curvada c/barra', category: 'Costas' },
  { name: 'Remada curvada c/halteres', category: 'Costas' },
  { name: 'Remada curvada máquina', category: 'Costas' },
  { name: 'Remada curvada no banco 45°', category: 'Costas' },
  { name: 'Remada curvada no Smith', category: 'Costas' },
  { name: 'Remada curvada pronada', category: 'Costas' },
  { name: 'Remada curvada supinada', category: 'Costas' },
  { name: 'Remada máquina', category: 'Costas' },
  { name: 'Remada máquina pegada neutra', category: 'Costas' },
  { name: 'Remada no cross', category: 'Costas' },
  { name: 'Remada no TRX', category: 'Costas' },
  { name: 'Remada Seven', category: 'Costas' },
  { name: 'Remada T', category: 'Costas' },
  { name: 'Remada T máquina', category: 'Costas' },
  { name: 'Remada T Seven', category: 'Costas' },
  { name: 'Serrote', category: 'Costas' },
  { name: 'Terra com barra', category: 'Costas' },
  { name: 'Terra no Smith', category: 'Costas' },
  { name: 'Voador invertido', category: 'Costas' },
  { name: 'Voador invertido pegada neutra inversa', category: 'Costas' },

  // --- OMBROS ---
  { name: 'Cruzamento de cabos invertidos no cross', category: 'Ombros' },
  { name: 'Desenvolvimento Arnold', category: 'Ombros' },
  { name: 'Desenvolvimento articulado', category: 'Ombros' },
  { name: 'Desenvolvimento c/halteres', category: 'Ombros' },
  { name: 'Desenvolvimento c/halteres pegada neutra', category: 'Ombros' },
  { name: 'Desenvolvimento máquina', category: 'Ombros' },
  { name: 'Desenvolvimento máquina neutra', category: 'Ombros' },
  { name: 'Desenvolvimento máquina pegada neutra', category: 'Ombros' },
  { name: 'Desenvolvimento no cross', category: 'Ombros' },
  { name: 'Desenvolvimento no Smith', category: 'Ombros' },
  { name: 'Desenvolvimento Seven', category: 'Ombros' },
  { name: 'Elevação frontal c/anilha', category: 'Ombros' },
  { name: 'Elevação frontal c/barra', category: 'Ombros' },
  { name: 'Elevação frontal c/halteres', category: 'Ombros' },
  { name: 'Elevação frontal c/halteres neutra', category: 'Ombros' },
  { name: 'Elevação frontal e lateral', category: 'Ombros' },
  { name: 'Elevação frontal no cross', category: 'Ombros' },
  { name: 'Elevação frontal unilateral', category: 'Ombros' },
  { name: 'Elevação lateral', category: 'Ombros' },
  { name: 'Elevação lateral c/halteres', category: 'Ombros' },
  { name: 'Elevação lateral máquina em pé', category: 'Ombros' },
  { name: 'Elevação lateral no cross', category: 'Ombros' },
  { name: 'Elevação lateral sentado', category: 'Ombros' },
  { name: 'Elevação lateral unilateral inclinado', category: 'Ombros' },
  { name: 'Encolhimento c/barra', category: 'Ombros' },
  { name: 'Encolhimento c/halteres', category: 'Ombros' },
  { name: 'Encolhimento máquina', category: 'Ombros' },
  { name: 'Encolhimento no cross', category: 'Ombros' },
  { name: 'Encolhimento no Smith', category: 'Ombros' },
  { name: 'Posterior de ombros c/halteres', category: 'Ombros' },
  { name: 'Posterior de ombros no cross', category: 'Ombros' },

  // --- BÍCEPS ---
  { name: 'Bíceps c/barra H', category: 'Bíceps' },
  { name: 'Bíceps concentrado unilateral', category: 'Bíceps' },
  { name: 'Bíceps máquina', category: 'Bíceps' },
  { name: 'Bíceps no cross polia alta', category: 'Bíceps' },
  { name: 'Rosca alternada c/halteres', category: 'Bíceps' },
  { name: 'Rosca concentrada', category: 'Bíceps' },
  { name: 'Rosca direta c/barra curvada', category: 'Bíceps' },
  { name: 'Rosca direta no cross', category: 'Bíceps' },
  { name: 'Rosca inversa c/barra curvada', category: 'Bíceps' },
  { name: 'Rosca inversa c/corda', category: 'Bíceps' },
  { name: 'Rosca martelo', category: 'Bíceps' },
  { name: 'Rosca martelo barra H', category: 'Bíceps' },
  { name: 'Rosca Scott', category: 'Bíceps' },
  { name: 'Rosca Scott no cross', category: 'Bíceps' },
  { name: 'Rosca simultânea c/halteres', category: 'Bíceps' },

  // --- TRÍCEPS ---
  { name: 'Tríceps banco', category: 'Tríceps' },
  { name: 'Tríceps banco Cimerian', category: 'Tríceps' },
  { name: 'Tríceps banco máquina', category: 'Tríceps' },
  { name: 'Tríceps coice c/halter', category: 'Tríceps' },
  { name: 'Tríceps corda', category: 'Tríceps' },
  { name: 'Tríceps francês', category: 'Tríceps' },
  { name: 'Tríceps na paralela', category: 'Tríceps' },
  { name: 'Tríceps no cross c/barra V', category: 'Tríceps' },
  { name: 'Tríceps no cross c/barrinha reta', category: 'Tríceps' },
  { name: 'Tríceps no graviton', category: 'Tríceps' },
  { name: 'Tríceps testa c/barra H', category: 'Tríceps' },
  { name: 'Tríceps testa c/halteres', category: 'Tríceps' },
  { name: 'Tríceps testa no cross', category: 'Tríceps' },

  // --- PERNAS / GLÚTEOS ---
  { name: 'Abdução em pé c/caneleira', category: 'Pernas' },
  { name: 'Abdutora', category: 'Pernas' },
  { name: 'Abdutora articulada', category: 'Pernas' },
  { name: 'Afundo c/halteres', category: 'Pernas' },
  { name: 'Afundo no Hack', category: 'Pernas' },
  { name: 'Afundo no Smith', category: 'Pernas' },
  { name: 'Afundo no step', category: 'Pernas' },
  { name: 'Afundo no TRX', category: 'Pernas' },
  { name: 'Agachamento', category: 'Pernas' },
  { name: 'Agachamento c/halteres', category: 'Pernas' },
  { name: 'Agachamento frontal c/barra', category: 'Pernas' },
  { name: 'Agachamento frontal no Hack', category: 'Pernas' },
  { name: 'Agachamento frontal no Smith', category: 'Pernas' },
  { name: 'Agachamento Hack', category: 'Pernas' },
  { name: 'Agachamento isométrico', category: 'Pernas' },
  { name: 'Agachamento livre c/barra', category: 'Pernas' },
  { name: 'Agachamento máquina', category: 'Pernas' },
  { name: 'Agachamento no TRX', category: 'Pernas' },
  { name: 'Agachamento sumô c/halter', category: 'Pernas' },
  { name: 'Avanço c/agachamento barra', category: 'Pernas' },
  { name: 'Avanço c/agachamento halteres', category: 'Pernas' },
  { name: 'Bom dia (Good Morning)', category: 'Pernas' },
  { name: 'Búlgaro c/halteres', category: 'Pernas' },
  { name: 'Búlgaro máquina', category: 'Pernas' },
  { name: 'Búlgaro no Smith', category: 'Pernas' },
  { name: 'Cadeira abdutora', category: 'Pernas' },
  { name: 'Cadeira adutora', category: 'Pernas' },
  { name: 'Cadeira extensora', category: 'Pernas' },
  { name: 'Cadeira flexora', category: 'Pernas' },
  { name: 'Elevação pélvica c/barra', category: 'Pernas' },
  { name: 'Elevação pélvica c/halter', category: 'Pernas' },
  { name: 'Elevação pélvica máquina', category: 'Pernas' },
  { name: 'Extensão no cross', category: 'Pernas' },
  { name: 'Flexora unilateral', category: 'Pernas' },
  { name: 'Flexão nórdica', category: 'Pernas' },
  { name: 'Good morning c/barra montada', category: 'Pernas' },
  { name: 'Leg articulado', category: 'Pernas' },
  { name: 'Leg press 180°', category: 'Pernas' },
  { name: 'Leg press 45°', category: 'Pernas' },
  { name: 'Leg press 45° Seven', category: 'Pernas' },
  { name: 'Leg press horizontal', category: 'Pernas' },
  { name: 'Mesa flexora', category: 'Pernas' },
  { name: 'Mesa flexora unilateral', category: 'Pernas' },
  { name: 'Panturrilha no banco', category: 'Pernas' },
  { name: 'Panturrilha em pé', category: 'Pernas' },
  { name: 'Panturrilha máquina', category: 'Pernas' },
  { name: 'Panturrilha no degrau', category: 'Pernas' },
  { name: 'Panturrilha no Smith', category: 'Pernas' },
  { name: 'Passada', category: 'Pernas' },
  { name: 'Passada c/agachamento barra', category: 'Pernas' },
  { name: 'Passada c/agachamento halteres', category: 'Pernas' },
  { name: 'Passada c/barra', category: 'Pernas' },
  { name: 'Passada c/halteres', category: 'Pernas' },
  { name: 'Passada com insistência', category: 'Pernas' },
  { name: 'Pelve Hammer', category: 'Pernas' },
  { name: 'Pelve máquina', category: 'Pernas' },
  { name: 'Pêndulo', category: 'Pernas' },
  { name: 'Recuo no Smith', category: 'Pernas' },
  { name: 'Stiff c/halter', category: 'Pernas' },
  { name: 'Stiff c/barra', category: 'Pernas' },
  { name: 'Stiff máquina', category: 'Pernas' },
  { name: 'Stiff no Smith', category: 'Pernas' },
  { name: 'Sumô c/anilha', category: 'Pernas' },
  { name: 'Sumô c/halter', category: 'Pernas' },

  // --- ANTEBRAÇO ---
  { name: 'Extensão de punho', category: 'Antebraço' },
  { name: 'Flexão de punho', category: 'Antebraço' },

  // --- CARDIO ---
  { name: 'Andar na esteira', category: 'Cardio' },
  { name: 'Correr na esteira', category: 'Cardio' },
  { name: 'Bicicleta ergométrica', category: 'Cardio' },
  { name: 'Elíptico', category: 'Cardio' },
  { name: 'Escada ergométrica', category: 'Cardio' },
  { name: 'Burpee', category: 'Cardio' },
  { name: 'Polichinelo', category: 'Cardio' },

  // --- MOBILIDADE (NOVOS) ---
  { name: 'Alongamento dinâmico de peitoral', category: 'Mobilidade' },
  { name: 'Gato e Vaca (Mobilidade Coluna)', category: 'Mobilidade' },
  { name: 'Mobilidade de ombro c/bastão', category: 'Mobilidade' },
  { name: 'Rotação torácica', category: 'Mobilidade' },
  { name: 'Mobilidade de quadril 90/90', category: 'Mobilidade' },
  { name: 'Mobilidade de tornozelo na parede', category: 'Mobilidade' },
  { name: 'Agachamento profundo (Cocorinhas)', category: 'Mobilidade' },
  { name: 'Worlds Greatest Stretch', category: 'Mobilidade' },
  { name: 'Liberação miofascial (Rolo)', category: 'Mobilidade' },
];

async function main() {
  console.log(`Iniciando inserção de ${exercises.length} exercícios...`);

  await prisma.exercise.createMany({
    data: exercises.map(ex => ({
      name: ex.name,
      category: ex.category,
      videoUrl: '', 
      instructions: `Execução correta do exercício ${ex.name}.`,
    })),
    skipDuplicates: true, // AQUI É O SEGREDO: Não duplica os que já existem
  });

  console.log('✅ Banco de exercícios atualizado com Mobilidade!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });