// lib/techniqueGuide.ts
// 📖 (2 out 2026) Títulos e explicações das técnicas do sistema, para a página pública do treino (/t). É uma CÓPIA dos textos de
// FIT-OS-FRONTEND/src/components/DayWorkout/techGuideData.js (o app do aluno mostra os mesmos). Se mudar lá, mude aqui (há um teste que compara).
// Os VÍDEOS vêm do banco (SystemTechniqueVideo), com o mesmo critério do app.

export type SystemTechnique = { title: string; desc: string };

export const SYSTEM_TECHNIQUES: Record<string, SystemTechnique> = {
  "21": { title: "MÉTODO 21", desc: "COMO EXECUTAR:\nDivida o movimento em 3 partes. Faça 7 repetições só na metade inferior do movimento, 7 na metade superior e 7 repetições completas. Totalizando 21 reps.\n\nPOR QUE FAZER:\nAumenta drasticamente o tempo sob tensão e o fluxo sanguíneo no local. É uma ótima ferramenta para quebrar platôs de estagnação." },
  "DROPSET": { title: "DROP-SET", desc: "COMO EXECUTAR:\nFaça as repetições até a falha muscular. Imediatamente reduza a carga (cerca de 20 a 30%) e continue o exercício até falhar novamente, sem nenhum descanso.\n\nPOR QUE FAZER:\nAumenta o estresse metabólico e recruta fibras musculares mais profundas que não foram fadigadas inicialmente. Excelente para hipertrofia e \"pump\" máximo." },
  "RESTPAUSE": { title: "REST-PAUSE", desc: "COMO EXECUTAR:\nRealize a série até a falha. Descanse apenas 10 a 15 segundos e volte a fazer o exercício com a MESMA carga até falhar de novo.\n\nPOR QUE FAZER:\nPermite realizar mais repetições totais com uma carga alta (tensão mecânica extrema), gerando um forte estímulo de hipertrofia na metade do tempo." },
  "BISET": { title: "BI-SET", desc: "COMO EXECUTAR:\nRealize o primeiro exercício e, sem nenhum descanso, passe imediatamente para a execução do segundo exercício acoplado.\n\nPOR QUE FAZER:\nAumenta a densidade do treino, eleva a frequência cardíaca e gera um estresse absurdo na musculatura alvo, otimizando seu tempo na academia." },
  "TRISET": { title: "TRI-SET", desc: "COMO EXECUTAR:\nRealize o primeiro exercício e, sem nenhum descanso, passe imediatamente para o segundo. Ao terminar o segundo, sem descanso, passe para o terceiro exercício acoplado.\n\nPOR QUE FAZER:\nEleva ainda mais a densidade do treino que o bi-set, aumentando bastante a frequência cardíaca e o estresse metabólico na região trabalhada em um tempo bem menor de academia." },
  "CLUSTERSET": { title: "CLUSTER SET", desc: "COMO EXECUTAR:\nDivida uma série pesada em pequenos blocos. (Ex: em vez de tentar 10 diretas, faça 3 reps, descanse 15s, faça mais 3 reps... até bater a meta).\n\nPOR QUE FAZER:\nPermite levantar mais carga total do que você aguentaria numa série contínua normal. Foca em força pura e hipertrofia miofibrilar sem perder a técnica." },
  "GVT": { title: "GVT (10x10)", desc: "COMO EXECUTAR:\nRealize 10 séries de 10 repetições com a mesma carga (cerca de 60% da sua força máxima) e descanso cravado de 60 segundos entre as séries.\n\nPOR QUE FAZER:\nÉ um choque brutal no corpo. O volume de treino extremo força o seu músculo a hipertrofiar para \"sobreviver\" ao estresse imposto." },
  "1_5_REPS": { title: "1 E MEIO (1.5 REPS)", desc: "COMO EXECUTAR:\nFaça o movimento completo, volte até a metade do caminho, suba novamente e então retorne à posição inicial. Isso conta como UMA repetição.\n\nPOR QUE FAZER:\nAumenta drasticamente o tempo sob tensão no ponto de maior dificuldade do exercício, maximizando o ganho de massa sem precisar colocar cargas extremas nas articulações." },
  "TUT": { title: "T.U.T. (TEMPO SOB TENSÃO)", desc: "COMO EXECUTAR:\nExecute as repetições de forma extremamente controlada, respeitando os segundos de cadência estipulados pelo Coach tanto na fase de descida (excêntrica) quanto na de subida (concêntrica). Sem jogar o peso.\n\nPOR QUE FAZER:\nImpede o uso de \"impulso\" para levantar o peso. Foca 100% da força no músculo alvo, gerando hipertrofia máxima com segurança." },
  "NORMAL": { title: "EXECUÇÃO PADRÃO", desc: "COMO EXECUTAR:\nSiga o número de séries e repetições estipulados, focando em manter a postura correta.\n\nPOR QUE FAZER:\nÉ a base da construção de força e hipertrofia. O foco aqui é na cadência (velocidade do movimento) e na progressão de carga treino a treino." },
};
